services:
  apache-sorteador:
    image: php:8.0-apache
    container_name: apache-sorteador
    volumes:
      - ./:/var/www/html
    networks:
     - npm-network  # Conecta ao NPM
    restart: unless-stopped
  networks:
    npm-network:
    external: true

  

